// ignore: unused_import
import 'package:intl/intl.dart' as intl;
import 'app_localizations.dart';

// ignore_for_file: type=lint

/// The translations for Portuguese (`pt`).
class AppLocalizationsPt extends AppLocalizations {
  AppLocalizationsPt([String locale = 'pt']) : super(locale);

  @override
  String get appName => 'Playground de Criptografia';

  @override
  String get caesar => 'César';

  @override
  String get diffieHellman => 'Diffie-Hellman';

  @override
  String get hash => 'Hash';

  @override
  String get caesarTryOut => 'Experimentar cifra de césar';

  @override
  String get diffieHellmanTryOut => 'Experimentar algoritmo de Diffie Hellman';

  @override
  String get hashCodeTryOut => 'Experimentar HashCode';

  @override
  String get enterTextToEncrypt => 'Digite o texto para criptografar';

  @override
  String get enterTextToDecrypt => 'Digite o texto para descriptografar';

  @override
  String get enterKey => 'Digite a chave';

  @override
  String get encryptedText => 'Texto criptografado';

  @override
  String get decryptedText => 'Texto descriptografado';

  @override
  String get userA => 'Usuário A';

  @override
  String get userB => 'Usuário B';

  @override
  String get privateKey => 'Chave Privada';

  @override
  String get publicKey => 'Chave Pública';

  @override
  String get sharedSecret => 'Segredo Compartilhado';

  @override
  String get globalParameters => 'Parâmetros Globais';

  @override
  String get globalParametersTitle => '1. Parâmetros Globais';

  @override
  String get primeModulus => 'Módulo Primo (P)';

  @override
  String get primeModulusHint => 'Um número primo grande (ex. 23)';

  @override
  String get generatorLabel => 'Gerador (G)';

  @override
  String get generatorHint => 'Uma raiz primitiva módulo P (ex. 5)';

  @override
  String get keyGenerationTitle => '2. Geração de Chaves';

  @override
  String get autoGenerated => 'Gerado automaticamente';

  @override
  String get computed => 'Calculado';

  @override
  String get publicKeyFormula => 'Chave Pública - (G^ chave privada) mod P';

  @override
  String get swap => 'Trocar';

  @override
  String get generator => 'G (Base / Gerador)';

  @override
  String get modulus => 'P (Módulo / Primo)';

  @override
  String get inputA => 'Entrada A';

  @override
  String get inputB => 'Entrada B';

  @override
  String get enterText => 'Digite o texto';

  @override
  String get dartHashCode => 'Hashcode do Dart';

  @override
  String get sha1HashCode => 'Hashcode SHA-1';

  @override
  String get sha256HashCode => 'Hashcode SHA-256';

  @override
  String get close => 'Fechar';

  @override
  String get aboutCaesarTitle => 'Sobre o algoritmo de Cifra de César';

  @override
  String get whatIsCaesarTitle => '📌 O que é';

  @override
  String get whatIsCaesarContent =>
      'A Cifra de César é um algoritmo de criptografia simétrica extremamente simples, baseado em substituição.\n\nEla funciona deslocando cada letra do alfabeto por um número fixo de posições.\n\nExemplo (deslocamento de 3):\nA → D\nB → E\nC → F\n...';

  @override
  String get originCaesarTitle => '🏛️ Origem Histórica';

  @override
  String get originCaesarContent =>
      'A cifra leva o nome de Júlio César, que a utilizava para proteger comunicações militares durante o período da República Romana (por volta de 50 a.C.).\n\nEle usava um deslocamento fixo de 3 letras para enviar mensagens aos seus generais.';

  @override
  String get howItWorksCaesarTitle => '⚙️ Como funciona (conceitualmente)';

  @override
  String get howItWorksCaesarContent =>
      '• Define-se um número inteiro chamado chave (shift)\n• Para cada letra:\n  - Localiza sua posição no alfabeto\n  - Soma o valor do deslocamento\n  - Aplica módulo 26 (para \"dar a volta\" no alfabeto)';

  @override
  String get characteristicsCaesarTitle => '🧠 Características Técnicas';

  @override
  String get characteristicsCaesarContent =>
      '• Tipo: Criptografia simétrica\n• Complexidade: Muito baixa\n• Segurança: Praticamente inexistente\n• Espaço de chaves: Apenas 25 possibilidades';

  @override
  String get usageHistoryCaesarTitle => '⚔️ Uso ao Longo da História';

  @override
  String get usageHistoryCaesarContent =>
      '• Comunicação militar na Roma Antiga\n• Base conceitual para criptografia clássica\n• Muito usada em ensino introdutório de segurança';

  @override
  String get limitationsCaesarTitle => '🚨 Limitações';

  @override
  String get limitationsCaesarContent =>
      '• Vulnerável a análise de frequência\n• Pode ser quebrada por força bruta em segundos\n• Não oferece confidencialidade real hoje';

  @override
  String get currentUsageCaesarTitle => '📱 Uso Atual';

  @override
  String get currentUsageCaesarContent =>
      '• Ensino de criptografia\n• Jogos e puzzles\n• Demonstração de conceitos básicos';

  @override
  String get aboutDiffieHellmanTitle => 'Sobre o algoritmo Diffie-Hellman';

  @override
  String get whatIsDiffieHellmanTitle => '📌 O que é';

  @override
  String get whatIsDiffieHellmanContent =>
      'O Algoritmo de Diffie-Hellman é um método de troca segura de chaves criptográficas.\n\nEle permite que duas partes criem uma chave secreta compartilhada sem nunca transmiti-la diretamente.';

  @override
  String get originDiffieHellmanTitle => '🏛️ Origem Histórica';

  @override
  String get originDiffieHellmanContent =>
      'Proposto em 1976 por:\n• Whitfield Diffie\n• Martin Hellman\n\nFoi o primeiro método prático de criptografia de chave pública.';

  @override
  String get ideaDiffieHellmanTitle => '💡 Ideia Central';

  @override
  String get ideaDiffieHellmanContent =>
      'Resolver o problema:\n\"Como duas pessoas podem compartilhar um segredo sem nunca terem se comunicado antes de forma segura?\"';

  @override
  String get howItWorksDiffieHellmanTitle =>
      '⚙️ Como funciona (conceitualmente)';

  @override
  String get howItWorksDiffieHellmanContent =>
      '1. Ambas as partes concordam publicamente em:\n   - Um número primo grande (p)\n   - Um gerador (g)\n2. Cada lado escolhe um segredo privado:\n   - A escolhe a\n   - B escolhe b\n3. Calculam valores públicos:';

  @override
  String get step45DiffieHellmanContent =>
      '4. Trocam A e B\n5. Calculam a chave compartilhada:';

  @override
  String get mathConceptDiffieHellmanTitle => '🧠 Conceito Matemático';

  @override
  String get mathConceptDiffieHellmanContent =>
      'Baseado no problema do logaritmo discreto.\n\nEsse problema é computacionalmente difícil de resolver, garantindo segurança.';

  @override
  String get characteristicsDiffieHellmanTitle =>
      '🛡️ Características Técnicas';

  @override
  String get characteristicsDiffieHellmanContent =>
      '• Tipo: Criptografia de chave pública\n• Objetivo: Troca de chaves, não criptografia direta\n• Segurança: Alta (com parâmetros corretos)\n• Base: Matemática modular';

  @override
  String get usageHistoryDiffieHellmanTitle => '🌐 Uso ao Longo da História';

  @override
  String get usageHistoryDiffieHellmanContent =>
      'Base para protocolos modernos como:\n• TLS/HTTPS\n• VPNs\n• SSH';

  @override
  String get currentUsageDiffieHellmanTitle => '📱 Uso Atual';

  @override
  String get currentUsageDiffieHellmanContent =>
      '• Estabelecimento de conexões seguras na internet\n• Aplicações bancárias\n• Comunicação criptografada';

  @override
  String get limitationsDiffieHellmanTitle => '🚨 Limitações';

  @override
  String get limitationsDiffieHellmanContent =>
      '• Vulnerável a ataques Man-in-the-Middle se não autenticado\n• Requer uso com certificados digitais';

  @override
  String get aboutHashTitle => 'Sobre o algoritmo de Hash';

  @override
  String get whatIsHashTitle => '📌 O que é';

  @override
  String get whatIsHashContent =>
      'Uma função hash transforma um dado de entrada de tamanho arbitrário em uma saída de tamanho fixo.';

  @override
  String get originHashTitle => '🏛️ Origem Histórica';

  @override
  String get originHashContent =>
      'O conceito surgiu dentro da computação, especialmente em estruturas de dados nos anos 1950–1970.\n\nCom o avanço da criptografia, surgiram funções hash criptográficas modernas como:\n• MD5\n• SHA-1\n• SHA-256';

  @override
  String get howItWorksHashTitle => '⚙️ Como funciona (conceitualmente)';

  @override
  String get howItWorksHashContent =>
      '• Recebe uma entrada qualquer\n• Aplica uma série de transformações matemáticas\n• Produz um valor fixo (hash)';

  @override
  String get importantPropertiesHashTitle => '🧠 Propriedades Importantes';

  @override
  String get importantPropertiesHashContent =>
      'Uma boa função hash deve ter:\n\n• Determinismo: Mesma entrada → mesma saída\n• Rapidez: Computação eficiente\n• Efeito avalanche: Pequena mudança → saída completamente diferente\n• Resistência a colisões: Difícil encontrar duas entradas com mesmo hash';

  @override
  String get characteristicsHashTitle => '🛡️ Características Técnicas';

  @override
  String get characteristicsHashContent =>
      '• Tipo: Função unidirecional\n• Não reversível\n• Usada para integridade e verificação';

  @override
  String get usageHistoryHashTitle => '🌐 Uso ao Longo da História';

  @override
  String get usageHistoryHashContent =>
      '• Estruturas de dados (HashMap, HashTable)\n• Armazenamento seguro de senhas\n• Assinaturas digitais';

  @override
  String get currentUsageHashTitle => '📱 Uso Atual';

  @override
  String get currentUsageHashContent =>
      '• Autenticação de usuários\n• Blockchain\n• Verificação de integridade de arquivos\n• Sistemas distribuídos';

  @override
  String get limitationsHashTitle => '🚨 Limitações';

  @override
  String get limitationsHashContent =>
      '• Colisões são possíveis (dependendo do algoritmo)\n• Algoritmos antigos (MD5, SHA-1) são considerados inseguros';

  @override
  String get importantObservationHashTitle =>
      '⚠️ Observação importante (arquitetural)';

  @override
  String get importantObservationHashContent =>
      'Hash ≠ criptografia reversível\n\n• Criptografia → pode ser revertida com chave\n• Hash → não pode ser revertido (idealmente)';

  @override
  String get dartHashCodeTitle => 'Dart hashCode';

  @override
  String get dartHashCodeDescription =>
      'O hashCode do Dart é um identificador numérico usado internamente para estruturas como Map e Set. Ele NÃO é criptograficamente seguro e pode variar entre execuções. Serve apenas para comparação rápida.';

  @override
  String get sha1HashCodeTitle => 'SHA-1';

  @override
  String get sha1HashCodeDescription =>
      'SHA-1 é um algoritmo de hash criptográfico que gera um valor de 160 bits. Hoje é considerado inseguro para uso em segurança, pois possui colisões conhecidas. É útil aqui apenas para fins didáticos.';

  @override
  String get sha256HashCodeTitle => 'SHA-256';

  @override
  String get sha256HashCodeDescription =>
      'SHA-256 é um algoritmo de hash criptográfico da família SHA-2 que gera um valor de 256 bits. É amplamente utilizado em segurança, blockchain e armazenamento seguro de dados.';

  @override
  String get inputTextTitle => 'Entrada de texto';

  @override
  String get inputTextDescription =>
      'Coloque uma entrada de dados para gerar os hashcodes, experimente mudar o texto e veja o resultado';

  @override
  String get reset => 'Redefinir';

  @override
  String get invalidInput => 'Entrada inválida';

  @override
  String get lettersOnly => 'Por favor, digite apenas letras';

  @override
  String get numbersOnly => 'Por favor, digite apenas números';

  @override
  String get theme => 'Tema';

  @override
  String get about => 'Sobre';

  @override
  String get localeNameDisplay => 'PT';

  @override
  String get randomlyGenerated => 'Número gerado aleatoriamente';

  @override
  String get welcomeTitle => 'Bem-vindo ao Playground de Criptografia';

  @override
  String get welcomeDescription =>
      'Explore algoritmos criptográficos, veja como funcionam por baixo dos panos e teste-os interativamente.';

  @override
  String get learnMoreAboutProject => 'Saiba mais sobre o projeto';

  @override
  String get exploreFeatures => 'Explorar Funcionalidades';

  @override
  String get cipherSuite => 'Criptografia de cifras e substituição';

  @override
  String get cipherSuiteShortTitle => 'Cifras';

  @override
  String get cipherSuiteDescription =>
      'Explore cifras de substituição clássicas e modernas, como a cifra de César.';

  @override
  String get symmetricSuite => 'Criptografia Simétrica';

  @override
  String get symmetricSuiteShortTitle => 'Criptog. Simétrica';

  @override
  String get symmetricSuiteDescription =>
      'Teste algoritmos de criptografia simétrica onde a mesma chave criptografa e descriptografa.';

  @override
  String get asymmetricSuite => 'Criptografia assimétrica';

  @override
  String get asymmetricSuiteShortTitle => 'Criptog. Assimétrica';

  @override
  String get asymmetricSuiteDescription =>
      'Aprenda sobre criptografia de chave pública e protocolos de troca de chaves como Diffie-Hellman.';

  @override
  String get dashboardDescription => 'Uma visão geral do painel';

  @override
  String get onboardingStep1Title => 'Bem-vindo ao Encryption Playground';

  @override
  String get onboardingStep1Message =>
      'Um espaço para aprender e experimentar criptografia de forma prática. Nenhum conhecimento prévio é necessário.';

  @override
  String get onboardingStep2Title => 'Experimente sem medo';

  @override
  String get onboardingStep2Message =>
      'Tudo acontece no seu dispositivo. Nenhum dado é enviado para servidores. Teste, erre e aprenda livremente.';

  @override
  String get onboardingStep3Title => 'O que você pode fazer';

  @override
  String get onboardingStep3Message =>
      'Criptografe e descriptografe textos, explore diferentes algoritmos, ajuste parâmetros e compare resultados lado a lado.';

  @override
  String get onboardingStep4Title => 'Comece pela Cifra de César';

  @override
  String get onboardingStep4Message =>
      'A Cifra de César é o algoritmo mais simples e um ótimo ponto de partida. Escolha uma suíte no menu e comece a experimentar!';

  @override
  String get onboardingSkip => 'Pular';

  @override
  String get onboardingNext => 'Próximo';

  @override
  String get onboardingStartExploring => 'Começar a Explorar';

  @override
  String get reviewTutorial => 'Rever Tutorial';

  @override
  String get hashSuite => 'Hashcode';

  @override
  String get hashSuiteDescription =>
      'Gere hashes criptográficos usando MD5, SHA-1, SHA-256 e outros.';

  @override
  String get cipherSuiteSubtitle =>
      'Cifras de substituição e transposição, métodos clássicos de criptografia.';

  @override
  String get caesarCipherDescription =>
      'Uma cifra de substituição clássica onde cada letra é deslocada por um número fixo de posições.';

  @override
  String get tryOut => 'Experimentar';

  @override
  String get symmetricSuiteSubtitle =>
      'Algoritmos que usam as mesmas chaves criptográficas para criptografia de texto simples e descriptografia de texto cifrado.';

  @override
  String get aesComingSoonTitle => 'AES (Em Breve)';

  @override
  String get aesComingSoonDescription =>
      'Advanced Encryption Standard é uma cifra de bloco simétrica escolhida pelo governo dos EUA para proteger informações classificadas.';

  @override
  String get comingSoon => 'Em Breve';

  @override
  String get asymmetricSuiteSubtitle =>
      'Algoritmos que exigem duas chaves separadas, uma das quais é secreta (ou privada) e a outra é pública.';

  @override
  String get diffieHellmanDescription =>
      'Um método de troca segura de chaves criptográficas em um canal público.';

  @override
  String get dashboard => 'Painel de Controle';

  @override
  String get keyComputationTitle => '3. Cálculo da Chave';

  @override
  String get userAComputesSharedKey =>
      'Usuário A calcula a chave compartilhada:';

  @override
  String get userBComputesSharedKey =>
      'Usuário B calcula a chave compartilhada:';

  @override
  String get resetParameters => 'Redefinir Parâmetros';

  @override
  String get aboutProjectTitle => 'Sobre o Projeto';

  @override
  String get aboutProjectText =>
      'Este projeto foi desenvolvido durante a disciplina de Segurança da Informação, durante o primeiro semestre do ano de 2026, com o intuito de demonstrar o funcionamento dos algoritmos de criptografia.';

  @override
  String get aboutApp => 'Sobre o aplicativo';

  @override
  String get version => 'Versão';

  @override
  String get developer => 'Desenvolvedor';

  @override
  String get license => 'Licença';

  @override
  String get contact => 'Contato';

  @override
  String get sourceCode => 'Código-fonte';

  @override
  String get hashFunctionsTitle => 'Funções Hash';

  @override
  String get hashFunctionsDescription =>
      'Uma função hash mapeia dados de tamanho arbitrário para valores de tamanho fixo. Tente alterar uma única letra e observe como toda a saída muda.';

  @override
  String get waitingForInput => 'Aguardando entrada...';

  @override
  String get inputBCompare => 'Entrada B (Comparar)';

  @override
  String get enterTextHere => 'Digite o texto aqui...';

  @override
  String get guide => 'Guia';

  @override
  String get caesarGuideStep1Title => 'Como funciona';

  @override
  String get caesarGuideStep1Message =>
      'A cifra de César substitui as letras deslocando-as no alfabeto.';

  @override
  String get caesarGuideStep2Title => 'Ajuste o deslocamento';

  @override
  String get caesarGuideStep2Message =>
      'Use o controle deslizante para alterar a chave de deslocamento e veja a fórmula e a visualização do alfabeto atualizarem.';

  @override
  String get caesarGuideStep3Title => 'Experimente';

  @override
  String get caesarGuideStep3Message =>
      'Digite o texto no campo de entrada para ver o resultado criptografado ou descriptografado. Use o botão Inverter para trocar de modo.';

  @override
  String get dhGuideStep1Title => 'O que é isso?';

  @override
  String get dhGuideStep1Message =>
      'Diffie-Hellman permite que dois usuários criem uma chave secreta compartilhada sem transmiti-la.';

  @override
  String get dhGuideStep2Title => 'Definir Parâmetros Globais';

  @override
  String get dhGuideStep2Message =>
      'Defina o número primo (P) e o gerador (G) na seção de parâmetros globais.';

  @override
  String get dhGuideStep3Title => 'Geração de Chaves';

  @override
  String get dhGuideStep3Message =>
      'As chaves privadas são geradas automaticamente e as chaves públicas são calculadas com a fórmula.';

  @override
  String get dhGuideStep4Title => 'Segredo Compartilhado';

  @override
  String get dhGuideStep4Message =>
      'Ambos os usuários chegam à mesma chave compartilhada, mesmo sem trocar chaves privadas.';

  @override
  String get hashGuideStep1Title => 'O que são Funções Hash?';

  @override
  String get hashGuideStep1Message =>
      'As funções hash transformam qualquer entrada em um valor de tamanho fixo, de forma irreversível.';

  @override
  String get hashGuideStep2Title => 'Compare os hashes';

  @override
  String get hashGuideStep2Message =>
      'Digite um texto na Entrada A e altere-o levemente na Entrada B para ver o efeito avalanche.';

  @override
  String get hashGuideStep3Title => 'Algoritmos Diferentes';

  @override
  String get hashGuideStep3Message =>
      'Observe as diferenças entre Dart hashCode, SHA-1 e SHA-256.';

  @override
  String get tooltipCaesarShift =>
      'Ajuste quantas posições cada letra se desloca no alfabeto';

  @override
  String get tooltipCaesarSwap =>
      'Alterne entre o modo de criptografia e descriptografia';

  @override
  String get tooltipCaesarFormula =>
      'A fórmula matemática usada para criptografar/descriptografar';

  @override
  String get tooltipDhPrime =>
      'Um número primo grande que ambas as partes concordam publicamente';

  @override
  String get tooltipDhGenerator =>
      'Uma raiz primitiva módulo P, usada como base para os cálculos';

  @override
  String get tooltipDhPrivateKey =>
      'Um número secreto conhecido apenas por este usuário';

  @override
  String get tooltipDhPublicKey =>
      'Calculado a partir da chave privada — seguro para compartilhar publicamente';

  @override
  String get tooltipDhSharedSecret =>
      'Ambos os usuários chegam à mesma chave sem compartilhar seus segredos';

  @override
  String get gNotPrimitiveRootInfo =>
      'ℹ️ G não é raiz primitiva de P. Para máxima segurança, G idealmente deveria ser uma raiz primitiva módulo P, para conseguir gerar todos os valores de chave possíveis. Isso não é obrigatório para o algoritmo funcionar, mas o torna mais forte.';

  @override
  String get tooltipHashDart =>
      'Hash interno do Dart — não é criptograficamente seguro';

  @override
  String get tooltipHashSha1 =>
      'Hash criptográfico de 160 bits — considerado inseguro hoje';

  @override
  String get tooltipHashSha256 =>
      'Hash seguro de 256 bits — amplamente utilizado na segurança moderna';

  @override
  String get gotIt => 'Entendi';

  @override
  String get next => 'Próximo';

  @override
  String get formula => 'Fórmula';

  @override
  String get shiftController => 'Controle da chave';

  @override
  String get plainText => 'Texto normal';

  @override
  String get cipherText => 'Texto criptografado';

  @override
  String get alphabetTransformation => 'Transformação do alfabeto';

  @override
  String get changeLanguage => 'Mudar idioma';

  @override
  String get resultAppearHere => 'O resultado aparecerá aqui';
}
