// ignore: unused_import
import 'package:intl/intl.dart' as intl;
import 'app_localizations.dart';

// ignore_for_file: type=lint

/// The translations for English (`en`).
class AppLocalizationsEn extends AppLocalizations {
  AppLocalizationsEn([String locale = 'en']) : super(locale);

  @override
  String get appName => 'Encryption Playground';

  @override
  String get caesar => 'Caesar';

  @override
  String get diffieHellman => 'Diffie-Hellman';

  @override
  String get hash => 'Hash';

  @override
  String get caesarTryOut => 'Caesar Try Out';

  @override
  String get diffieHellmanTryOut => 'Diffie Hellman try out';

  @override
  String get hashCodeTryOut => 'HashCode try out';

  @override
  String get enterTextToEncrypt => 'Enter text to encrypt';

  @override
  String get enterTextToDecrypt => 'Enter text to decrypt';

  @override
  String get enterKey => 'Enter key';

  @override
  String get encryptedText => 'Encrypted text';

  @override
  String get decryptedText => 'Decrypted text';

  @override
  String get userA => 'User A';

  @override
  String get userB => 'User B';

  @override
  String get privateKey => 'Private Key';

  @override
  String get publicKey => 'Public Key';

  @override
  String get sharedSecret => 'Shared Secret';

  @override
  String get globalParameters => 'Global Parameters';

  @override
  String get globalParametersTitle => '1. Global Parameters';

  @override
  String get primeModulus => 'Prime Modulus (P)';

  @override
  String get primeModulusHint => 'A large prime number (e.g. 23)';

  @override
  String get generatorLabel => 'Generator (G)';

  @override
  String get generatorHint => 'A primitive root modulo P (e.g. 5)';

  @override
  String get keyGenerationTitle => '2. Key Generation';

  @override
  String get autoGenerated => 'Auto-generated';

  @override
  String get computed => 'Computed';

  @override
  String get publicKeyFormula => 'Public Key - (G^ private key) mod P';

  @override
  String get swap => 'Swap';

  @override
  String get generator => 'G (Base / Generator)';

  @override
  String get modulus => 'P (Modulus / Prime)';

  @override
  String get inputA => 'Input A';

  @override
  String get inputB => 'Input B';

  @override
  String get enterText => 'Enter text';

  @override
  String get dartHashCode => 'Dart hashcode';

  @override
  String get sha1HashCode => 'sha-1 hashcode';

  @override
  String get sha256HashCode => 'SHA-256 HashCode';

  @override
  String get close => 'Close';

  @override
  String get aboutCaesarTitle => 'About Caesar Cipher algorithm';

  @override
  String get whatIsCaesarTitle => '📌 What is it';

  @override
  String get whatIsCaesarContent =>
      'The Caesar Cipher is an extremely simple symmetric encryption algorithm based on substitution.\n\nIt works by shifting each letter of the alphabet by a fixed number of positions.\n\nExample (shift of 3):\nA → D\nB → E\nC → F\n...';

  @override
  String get originCaesarTitle => '🏛️ Historical Origin';

  @override
  String get originCaesarContent =>
      'The cipher is named after Julius Caesar, who used it to protect military communications during the Roman Republic period (around 50 BC).\n\nHe used a fixed shift of 3 letters to send messages to his generals.';

  @override
  String get howItWorksCaesarTitle => '⚙️ How it works (conceptually)';

  @override
  String get howItWorksCaesarContent =>
      '• An integer called the shift value (k) is defined\n• For each letter:\n  - Locate its position in the alphabet\n  - Add the shift value\n  - Apply modulo 26 (to \"wrap around\" the alphabet)';

  @override
  String get characteristicsCaesarTitle => '🧠 Technical Characteristics';

  @override
  String get characteristicsCaesarContent =>
      '• Type: Symmetric encryption\n• Complexity: Very low\n• Security: Practically non-existent\n• Key space: Only 25 possibilities';

  @override
  String get usageHistoryCaesarTitle => '⚔️ Usage throughout History';

  @override
  String get usageHistoryCaesarContent =>
      '• Military communication in Ancient Rome\n• Conceptual basis for classical cryptography\n• Widely used in introductory security teaching';

  @override
  String get limitationsCaesarTitle => '🚨 Limitations';

  @override
  String get limitationsCaesarContent =>
      '• Vulnerable to frequency analysis\n• Can be broken by brute force in seconds\n• Does not offer real confidentiality today';

  @override
  String get currentUsageCaesarTitle => '📱 Current Usage';

  @override
  String get currentUsageCaesarContent =>
      '• Teaching cryptography\n• Games and puzzles\n• Demonstration of basic concepts';

  @override
  String get aboutDiffieHellmanTitle => 'About Diffie-Hellman algorithm';

  @override
  String get whatIsDiffieHellmanTitle => '📌 What is it';

  @override
  String get whatIsDiffieHellmanContent =>
      'The Diffie-Hellman algorithm is a method for secure cryptographic key exchange.\n\nIt allows two parties to create a shared secret key without ever transmitting it directly.';

  @override
  String get originDiffieHellmanTitle => '🏛️ Historical Origin';

  @override
  String get originDiffieHellmanContent =>
      'Proposed in 1976 by:\n• Whitfield Diffie\n• Martin Hellman\n\nIt was the first practical method of public-key cryptography.';

  @override
  String get ideaDiffieHellmanTitle => '💡 Central Idea';

  @override
  String get ideaDiffieHellmanContent =>
      'Solving the problem:\n\"How can two people share a secret without ever having communicated securely before?\"';

  @override
  String get howItWorksDiffieHellmanTitle => '⚙️ How it works (conceptually)';

  @override
  String get howItWorksDiffieHellmanContent =>
      '1. Both parties publicly agree on:\n   - A large prime number (p)\n   - A generator (g)\n2. Each side chooses a private secret:\n   - A chooses a\n   - B chooses b\n3. Calculate public values:';

  @override
  String get step45DiffieHellmanContent =>
      '4. Exchange A and B\n5. Calculate shared key:';

  @override
  String get mathConceptDiffieHellmanTitle => '🧠 Mathematical Concept';

  @override
  String get mathConceptDiffieHellmanContent =>
      'Based on the discrete logarithm problem.\n\nThis problem is computationally hard to solve, ensuring security.';

  @override
  String get characteristicsDiffieHellmanTitle =>
      '🛡️ Technical Characteristics';

  @override
  String get characteristicsDiffieHellmanContent =>
      '• Type: Public-key cryptography\n• Goal: Key exchange, not direct encryption\n• Security: High (with correct parameters)\n• Base: Modular mathematics';

  @override
  String get usageHistoryDiffieHellmanTitle => '🌐 Usage throughout History';

  @override
  String get usageHistoryDiffieHellmanContent =>
      'Basis for modern protocols like:\n• TLS/HTTPS\n• VPNs\n• SSH';

  @override
  String get currentUsageDiffieHellmanTitle => '📱 Current Usage';

  @override
  String get currentUsageDiffieHellmanContent =>
      '• Establishing secure connections on the internet\n• Banking applications\n• Encrypted communication';

  @override
  String get limitationsDiffieHellmanTitle => '🚨 Limitations';

  @override
  String get limitationsDiffieHellmanContent =>
      '• Vulnerable to Man-in-the-Middle attacks if not authenticated\n• Requires use with digital certificates';

  @override
  String get aboutHashTitle => 'About Hash algorithm';

  @override
  String get whatIsHashTitle => '📌 What is it';

  @override
  String get whatIsHashContent =>
      'A hash function transforms input data of arbitrary size into an output of fixed size.';

  @override
  String get originHashTitle => '🏛️ Historical Origin';

  @override
  String get originHashContent =>
      'The concept emerged within computing, especially in data structures in the 1950s–1970s.\n\nWith the advancement of cryptography, modern cryptographic hash functions emerged such as:\n• MD5\n• SHA-1\n• SHA-256';

  @override
  String get howItWorksHashTitle => '⚙️ How it works (conceptually)';

  @override
  String get howItWorksHashContent =>
      '• Receives any input\n• Applies a series of mathematical transformations\n• Produces a fixed value (hash)';

  @override
  String get importantPropertiesHashTitle => '🧠 Important Properties';

  @override
  String get importantPropertiesHashContent =>
      'A good hash function must have:\n\n• Determinism: Same input → same output\n• Speed: Efficient computation\n• Avalanche effect: Small change → completely different output\n• Collision resistance: Difficult to find two inputs with the same hash';

  @override
  String get characteristicsHashTitle => '🛡️ Technical Characteristics';

  @override
  String get characteristicsHashContent =>
      '• Type: One-way function\n• Non-reversible\n• Used for integrity and verification';

  @override
  String get usageHistoryHashTitle => '🌐 Usage throughout History';

  @override
  String get usageHistoryHashContent =>
      '• Data structures (HashMap, HashTable)\n• Secure password storage\n• Digital signatures';

  @override
  String get currentUsageHashTitle => '📱 Current Usage';

  @override
  String get currentUsageHashContent =>
      '• User authentication\n• Blockchain\n• File integrity verification\n• Distributed systems';

  @override
  String get limitationsHashTitle => '🚨 Limitations';

  @override
  String get limitationsHashContent =>
      '• Collisions are possible (depending on the algorithm)\n• Old algorithms (MD5, SHA-1) are considered insecure';

  @override
  String get importantObservationHashTitle =>
      '⚠️ Important Observation (architectural)';

  @override
  String get importantObservationHashContent =>
      'Hash ≠ reversible encryption\n\n• Encryption → can be reversed with a key\n• Hash → cannot be reversed (ideally)';

  @override
  String get dartHashCodeTitle => 'Dart hashCode';

  @override
  String get dartHashCodeDescription =>
      'Dart\'s hashCode is a numeric identifier used internally for structures like Map and Set. It is NOT cryptographically secure and may vary between executions. It serves only for quick comparison.';

  @override
  String get sha1HashCodeTitle => 'SHA-1';

  @override
  String get sha1HashCodeDescription =>
      'SHA-1 is a cryptographic hash algorithm that generates a 160-bit value. Today it is considered insecure for security use as it has known collisions. It is useful here only for educational purposes.';

  @override
  String get sha256HashCodeTitle => 'SHA-256';

  @override
  String get sha256HashCodeDescription =>
      'SHA-256 is a cryptographic hash algorithm from the SHA-2 family that generates a 256-bit value. It is widely used in security, blockchain, and secure data storage.';

  @override
  String get inputTextTitle => 'Text Input';

  @override
  String get inputTextDescription =>
      'Enter data to generate hashcodes, try changing the text and see the result';

  @override
  String get reset => 'Reset';

  @override
  String get invalidInput => 'Invalid input';

  @override
  String get lettersOnly => 'Please enter letters only';

  @override
  String get numbersOnly => 'Please enter numbers only';

  @override
  String get theme => 'Theme';

  @override
  String get about => 'About';

  @override
  String get localeNameDisplay => 'EN';

  @override
  String get randomlyGenerated => 'Randomly generated number';

  @override
  String get welcomeTitle => 'Welcome to Encryption Playground';

  @override
  String get welcomeDescription =>
      'Explore cryptographic algorithms, see how they work under the hood, and test them out interactively.';

  @override
  String get learnMoreAboutProject => 'Learn more about the project';

  @override
  String get exploreFeatures => 'Explore Features';

  @override
  String get cipherSuite => 'Ciphers and Substitution';

  @override
  String get cipherSuiteShortTitle => 'Ciphers';

  @override
  String get cipherSuiteDescription =>
      'Explore classic and modern substitution ciphers like the Caesar cipher.';

  @override
  String get symmetricSuite => 'Symmetric encryption';

  @override
  String get symmetricSuiteShortTitle => 'Symmetric';

  @override
  String get symmetricSuiteDescription =>
      'Test symmetric encryption algorithms where the same key encrypts and decrypts.';

  @override
  String get asymmetricSuite => 'Asymmetric encryption';

  @override
  String get asymmetricSuiteShortTitle => 'Asymmetric';

  @override
  String get asymmetricSuiteDescription =>
      'Learn about public-key cryptography and key exchange protocols like Diffie-Hellman.';

  @override
  String get dashboardDescription => 'A dashboard overview';

  @override
  String get onboardingStep1Title => 'Welcome to Encryption Playground';

  @override
  String get onboardingStep1Message =>
      'A space to learn and experiment with cryptography in a practical way. No prior knowledge is necessary.';

  @override
  String get onboardingStep2Title => 'Experiment without fear';

  @override
  String get onboardingStep2Message =>
      'Everything happens on your device. No data is sent to servers. Test, make mistakes, and learn freely.';

  @override
  String get onboardingStep3Title => 'What you can do';

  @override
  String get onboardingStep3Message =>
      'Encrypt and decrypt texts, explore different algorithms, adjust parameters, and compare results side by side.';

  @override
  String get onboardingStep4Title => 'Start with Caesar Cipher';

  @override
  String get onboardingStep4Message =>
      'Caesar Cipher is the simplest algorithm and a great starting point. Choose a suite from the menu and start experimenting!';

  @override
  String get onboardingSkip => 'Skip';

  @override
  String get onboardingNext => 'Next';

  @override
  String get onboardingStartExploring => 'Start Exploring';

  @override
  String get reviewTutorial => 'Review Tutorial';

  @override
  String get hashSuite => 'Hashcode';

  @override
  String get hashSuiteDescription =>
      'Generate cryptographic hashes using MD5, SHA-1, SHA-256 and more.';

  @override
  String get cipherSuiteSubtitle =>
      'Substitution and transposition ciphers, classical encryption methods.';

  @override
  String get caesarCipherDescription =>
      'A classic substitution cipher where each letter is shifted by a fixed number of positions.';

  @override
  String get tryOut => 'Try out';

  @override
  String get symmetricSuiteSubtitle =>
      'Algorithms that use the same cryptographic keys for both encryption of plaintext and decryption of ciphertext.';

  @override
  String get aesComingSoonTitle => 'AES (Coming Soon)';

  @override
  String get aesComingSoonDescription =>
      'Advanced Encryption Standard is a symmetric block cipher chosen by the U.S. government to protect classified information.';

  @override
  String get comingSoon => 'Coming Soon';

  @override
  String get asymmetricSuiteSubtitle =>
      'Algorithms that require two separate keys, one of which is secret (or private) and one of which is public.';

  @override
  String get diffieHellmanDescription =>
      'A method of securely exchanging cryptographic keys over a public channel.';

  @override
  String get dashboard => 'Dashboard';

  @override
  String get keyComputationTitle => '3. Key Computation';

  @override
  String get userAComputesSharedKey => 'User A computes shared key:';

  @override
  String get userBComputesSharedKey => 'User B computes shared key:';

  @override
  String get resetParameters => 'Reset Parameters';

  @override
  String get aboutProjectTitle => 'About the Project';

  @override
  String get aboutProjectText =>
      'This project was developed during the Information Security course, during the first semester of 2026, to demonstrate how cryptography algorithms work.';

  @override
  String get aboutApp => 'About the application';

  @override
  String get version => 'Version';

  @override
  String get developer => 'Developer';

  @override
  String get license => 'License';

  @override
  String get contact => 'Contact';

  @override
  String get sourceCode => 'Source Code';

  @override
  String get hashFunctionsTitle => 'Hash Functions';

  @override
  String get hashFunctionsDescription =>
      'A hash function maps data of arbitrary size to fixed-size values. Try altering a single letter and notice how the entire output changes.';

  @override
  String get waitingForInput => 'Waiting for input...';

  @override
  String get inputBCompare => 'Input B (Compare)';

  @override
  String get enterTextHere => 'Enter text here...';

  @override
  String get guide => 'Guide';

  @override
  String get caesarGuideStep1Title => 'How it works';

  @override
  String get caesarGuideStep1Message =>
      'The Caesar cipher substitutes letters by shifting them in the alphabet.';

  @override
  String get caesarGuideStep2Title => 'Adjust the shift';

  @override
  String get caesarGuideStep2Message =>
      'Use the slider to change the shift key and see the formula and alphabet visualization update.';

  @override
  String get caesarGuideStep3Title => 'Try it out';

  @override
  String get caesarGuideStep3Message =>
      'Enter text in the input field to see the encrypted or decrypted result. Use the Swap button to switch modes.';

  @override
  String get dhGuideStep1Title => 'What is this?';

  @override
  String get dhGuideStep1Message =>
      'Diffie-Hellman allows two users to create a shared secret key without transmitting it.';

  @override
  String get dhGuideStep2Title => 'Set Global Parameters';

  @override
  String get dhGuideStep2Message =>
      'Set the prime (P) and generator (G) in the global parameters section.';

  @override
  String get dhGuideStep3Title => 'Key Generation';

  @override
  String get dhGuideStep3Message =>
      'Private keys are auto-generated and public keys are calculated with the formula.';

  @override
  String get dhGuideStep4Title => 'Shared Secret';

  @override
  String get dhGuideStep4Message =>
      'Both users arrive at the same shared key, even without exchanging private keys.';

  @override
  String get hashGuideStep1Title => 'What are Hash Functions?';

  @override
  String get hashGuideStep1Message =>
      'Hash functions transform any input into a fixed-size value, irreversibly.';

  @override
  String get hashGuideStep2Title => 'Compare the hashes';

  @override
  String get hashGuideStep2Message =>
      'Type text in Input A and slightly alter it in Input B to see the avalanche effect.';

  @override
  String get hashGuideStep3Title => 'Different Algorithms';

  @override
  String get hashGuideStep3Message =>
      'Observe the differences between Dart hashCode, SHA-1, and SHA-256.';

  @override
  String get tooltipCaesarShift =>
      'Adjust how many positions each letter shifts in the alphabet';

  @override
  String get tooltipCaesarSwap =>
      'Switch between encryption and decryption mode';

  @override
  String get tooltipCaesarFormula =>
      'The mathematical formula used to encrypt/decrypt';

  @override
  String get tooltipDhPrime =>
      'A large prime number that both parties agree on publicly';

  @override
  String get tooltipDhGenerator =>
      'A primitive root modulo P, used as the base for calculations';

  @override
  String get tooltipDhPrivateKey => 'A secret number known only to this user';

  @override
  String get tooltipDhPublicKey =>
      'Calculated from the private key — safe to share publicly';

  @override
  String get tooltipDhSharedSecret =>
      'Both users arrive at the same key without sharing their secrets';

  @override
  String get tooltipHashDart =>
      'Dart\'s internal hash — not cryptographically secure';

  @override
  String get tooltipHashSha1 =>
      '160-bit cryptographic hash — considered insecure today';

  @override
  String get tooltipHashSha256 =>
      '256-bit secure hash — widely used in modern security';

  @override
  String get gotIt => 'Got it';

  @override
  String get next => 'Next';

  @override
  String get formula => 'Formula';

  @override
  String get shiftController => 'Shit Controller';

  @override
  String get plainText => 'Plaintext';

  @override
  String get cipherText => 'Ciphertext';

  @override
  String get alphabetTransformation => 'Alphabet transformation';

  @override
  String get changeLanguage => 'Change language';

  @override
  String get resultAppearHere => 'Result will appear here';
}
