name: encryption_playground
description: "The educational playground for encryption algorithms"

publish_to: 'none'

version: 1.1.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  crypto: ^3.0.7
  google_fonts: ^8.0.2
  url_launcher: ^6.2.5
  shared_preferences: ^2.2.3
  package_info_plus: ^9.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1

flutter:

  uses-material-design: true
  generate: true


  assets:
    - assets/dark_logo_full.png
    - assets/light_logo_full.png
    - assets/dark_logo_small.png
    - assets/light_logo_small.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/dark_logo_small.png"
  web:
    generate: true
    image_path: "assets/dark_logo_small.png"
    backgroundColor: "#0A0E14"
    themeColor: "#0A0E14"
  android_12: 
    color: "#0A0E14"
    image: "assets/dark_logo_small.png"
flutter_native_splash:
  color: "#0A0E14"
  color_dark: "#0A0E14"
  image: "assets/dark_logo_small.png"
  android_12:
    color: "#0A0E14"
  android: true
  ios: true
  web: true
