import 'package:encryption_playground/features/diffie_hellman/presentation/pages/diffie_hellman_try_out.dart';
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:provider/provider.dart';

import '../../../../shared/theme/app_colors.dart';
import '../../../../l10n/app_localizations.dart';
import '../diffie_hellman_controller.dart';

/// Responsible for displaying the Key Generation section for the [DiffieHellmanTryOut] page.
class DHTryOutKeyGenerationSection extends StatelessWidget {
  const DHTryOutKeyGenerationSection({
    super.key,
  }) : isMobileLayout = false;

  const DHTryOutKeyGenerationSection.mobileLayout({
    super.key,
  }) : isMobileLayout = true;

  final bool isMobileLayout;

  @override
  Widget build(BuildContext context) {
    final controller = context.watch<DiffieHellmanController>();

    return Container(
      padding: const EdgeInsets.all(24),
      decoration: BoxDecoration(
        color: AppColors.darkSurfaceContainer,
        borderRadius: BorderRadius.circular(2),
        border: Border.all(color: AppColors.darkOutlineVariant),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            AppLocalizations.of(context)!.keyGenerationTitle,
            style: GoogleFonts.spaceGrotesk(
              fontSize: 20,
              fontWeight: FontWeight.w700,
              color: AppColors.darkOnSurface,
            ),
          ),
          const SizedBox(height: 24),

          // User A
          _buildUserSection(
            context,
            AppLocalizations.of(context)!.userA,
            controller.userAPrivateKeyController,
            controller.userAPublicKeyController,
            AppColors.darkPrimary,
          ),
          const Padding(
            padding: EdgeInsets.symmetric(vertical: 24.0),
            child: Divider(color: AppColors.darkOutlineVariant),
          ),

          // User B
          _buildUserSection(
            context,
            AppLocalizations.of(context)!.userB,
            controller.userBPrivateKeyController,
            controller.userBPublicKeyController,
            AppColors.darkSecondary,
          ),
        ],
      ),
    );
  }

  Widget _buildUserSection(BuildContext context, String title, TextEditingController privateController, TextEditingController publicController, Color accentColor) {
    final privateKeyField = Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          AppLocalizations.of(context)!.privateKey,
          style: GoogleFonts.inter(
            fontSize: 14,
            fontWeight: FontWeight.w600,
            color: AppColors.darkOnSurfaceVariant,
          ),
        ),
        const SizedBox(height: 8),
        TextField(
          controller: privateController,
          readOnly: true,
          decoration: InputDecoration(
              hintText: AppLocalizations.of(context)!.autoGenerated,
              prefixIcon: Icon(Icons.vpn_key_outlined, size: 20),
              fillColor: Colors.black
          ),
        ),
      ],
    );
    final publicKeyField = Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          AppLocalizations.of(context)!.publicKeyFormula,
          style: GoogleFonts.inter(
            fontSize: 14,
            fontWeight: FontWeight.w600,
            color: AppColors.darkOnSurfaceVariant,
          ),
        ),
        const SizedBox(height: 8),
        TextField(
          controller: publicController,
          readOnly: true,
          decoration: InputDecoration(
              hintText: AppLocalizations.of(context)!.computed,
              prefixIcon: Icon(Icons.public, size: 20),
              fillColor: Colors.black
          ),
        ),
      ],
    );

    return Container(
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: AppColors.darkSurfaceContainerHigh,
        borderRadius: BorderRadius.circular(2),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              Icon(Icons.person, color: accentColor),
              const SizedBox(width: 8),
              Text(
                title,
                style: GoogleFonts.spaceGrotesk(
                  fontSize: 18,
                  fontWeight: FontWeight.w600,
                  color: accentColor,
                ),
              ),
            ],
          ),
          const SizedBox(height: 16),

          isMobileLayout ?
          Column(
              children: [
                privateKeyField,
                const SizedBox(height: 16),
                publicKeyField,
              ],
            )
          :
          Row(
            crossAxisAlignment: CrossAxisAlignment.end,
            children: [
              Expanded(child: privateKeyField),
              const SizedBox(width: 16),
              Expanded(child: publicKeyField),
            ],
          ),
        ],
      ),
    );
  }
}
