import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:provider/provider.dart';

import '../../../../l10n/app_localizations.dart';
import '../diffie_hellman_controller.dart';

/// Responsible for displaying the Key Generation section for the [DiffieHellmanTryOut] page.
class DHTryOutKeyGenerationSection extends StatelessWidget {
  const DHTryOutKeyGenerationSection({
    super.key,
  }) : isMobileLayout = false;

  const DHTryOutKeyGenerationSection.mobileLayout({
    super.key,
  }) : isMobileLayout = true;

  final bool isMobileLayout;

  @override
  Widget build(BuildContext context) {
    final controller = context.watch<DiffieHellmanController>();
    final colorScheme = Theme.of(context).colorScheme;

    return Container(
      padding: const EdgeInsets.all(24),
      decoration: BoxDecoration(
        color: colorScheme.surfaceContainer,
        borderRadius: BorderRadius.circular(2),
        border: Border.all(color: colorScheme.outlineVariant),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            AppLocalizations.of(context)!.keyGenerationTitle,
            style: GoogleFonts.spaceGrotesk(
              fontSize: 20,
              fontWeight: FontWeight.w700,
              color: colorScheme.onSurface,
            ),
          ),
          const SizedBox(height: 24),

          // User A
          _buildUserSection(
            context,
            AppLocalizations.of(context)!.userA,
            controller.userAPrivateKeyController,
            controller.userAPublicKeyController,
            colorScheme.primary,
          ),
          Padding(
            padding: const EdgeInsets.symmetric(vertical: 24.0),
            child: Divider(color: colorScheme.outlineVariant),
          ),

          // User B
          _buildUserSection(
            context,
            AppLocalizations.of(context)!.userB,
            controller.userBPrivateKeyController,
            controller.userBPublicKeyController,
            colorScheme.secondary,
          ),
        ],
      ),
    );
  }

  Widget _buildUserSection(BuildContext context, String title, TextEditingController privateController, TextEditingController publicController, Color accentColor) {
    final colorScheme = Theme.of(context).colorScheme;
    final privateKeyField = Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          AppLocalizations.of(context)!.privateKey,
          style: GoogleFonts.inter(
            fontSize: 14,
            fontWeight: FontWeight.w600,
            color: colorScheme.onSurfaceVariant,
          ),
        ),
        const SizedBox(height: 8),
        Tooltip(
          message: AppLocalizations.of(context)!.tooltipDhPrivateKey,
          child: TextField(
            controller: privateController,
            readOnly: true,
            decoration: InputDecoration(
                hintText: AppLocalizations.of(context)!.autoGenerated,
                prefixIcon: Icon(Icons.vpn_key_outlined, size: 20),
                fillColor: colorScheme.surface
            ),
          ),
        ),
      ],
    );
    final publicKeyField = Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          AppLocalizations.of(context)!.publicKeyFormula,
          style: GoogleFonts.inter(
            fontSize: 14,
            fontWeight: FontWeight.w600,
            color: colorScheme.onSurfaceVariant,
          ),
        ),
        const SizedBox(height: 8),
        Tooltip(
          message: AppLocalizations.of(context)!.tooltipDhPublicKey,
          child: TextField(
            controller: publicController,
            readOnly: true,
            decoration: InputDecoration(
                hintText: AppLocalizations.of(context)!.computed,
                prefixIcon: Icon(Icons.public, size: 20),
                fillColor: colorScheme.surface
            ),
          ),
        ),
      ],
    );

    return Container(
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: colorScheme.surfaceContainerHigh,
        borderRadius: BorderRadius.circular(2),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              Icon(Icons.person, color: accentColor),
              const SizedBox(width: 8),
              Text(
                title,
                style: GoogleFonts.spaceGrotesk(
                  fontSize: 18,
                  fontWeight: FontWeight.w600,
                  color: accentColor,
                ),
              ),
            ],
          ),
          const SizedBox(height: 16),

          isMobileLayout ?
          Column(
              children: [
                privateKeyField,
                const SizedBox(height: 16),
                publicKeyField,
              ],
            )
          :
          Row(
            crossAxisAlignment: CrossAxisAlignment.end,
            children: [
              Expanded(child: privateKeyField),
              const SizedBox(width: 16),
              Expanded(child: publicKeyField),
            ],
          ),
        ],
      ),
    );
  }
}
