name: Build & Deploy Flutter Web

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Cache Flutter
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            flutter
          key: flutter-${{ runner.os }}-${{ hashFiles('**/pubspec.lock') }}

      - name: Clone Flutter
        run: |
          if [ ! -d "flutter" ]; then
            git clone https://github.com/flutter/flutter.git --depth 1
          fi

      - name: Set PATH
        run: echo "$PWD/flutter/bin" >> $GITHUB_PATH

      - name: Enable Web
        run: flutter config --enable-web

      - name: Install deps
        run: flutter pub get

      - name: Build Web
        run: flutter build web --release

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy to Vercel
        run: vercel build/web --prod --token=${{ secrets.VERCEL_TOKEN }} --confirm
